### ISSUE TITLE
Problems in IE11

### ISSUE THREAD

**Issue by martinbdz** [jillix/svg.pan-zoom.js#15]
There are some problems with IE which I was not able to fix yet. The panning issue might be related to the svg.draggy.js issue.
Zooming is not possible because IE does not have the value e.wheelDeltaY in the doZoom function. I think it is using e.wheelDelta.

**Comment by IonicaBizau** [comment]
> The panning issue might be related to the svg.draggy.js issue.

Yeah, actually the panning is done in this library. But it could be that it's the same issue since it's a group element.

> Zooming is not possible because IE does not have the value e.wheelDeltaY in the doZoom function. I think it is using e.wheelDelta.

Yes, would appreciate contributions in this direction! :sparkle:

**Comment by IonicaBizau** [comment]
@silviubogan Can you please test this out on your machine?

**Comment by martinbdz** [comment]
If you change the following line in the doZoom function

``` javascript
e.deltaY = e.deltaY || e.wheelDeltaY;
```

to

``` javascript
e.deltaY = e.deltaY || e.wheelDeltaY || e.wheelDelta;
```

and add the svg.js fix for transformations (https://github.com/wout/svg.js/pull/372) it works. The only problem is that the zoom is reversed in IE. I can create a pull request if I find a solution for the problem.

**Comment by IonicaBizau** [comment]
> The only problem is that the zoom is reversed in IE

Can you compare it with Chrome? If IE behavior is different than Chrome, probably instead of `e.wheelDelta` you have to use `-e.wheelDelta`. If they are zoomed in the same direction and you want the reverse direction, you have to specify the [`zoomSpeed`](https://github.com/jillix/svg.pan-zoom.js#params) option (which defaults to `-1`) to `1`. :four_leaf_clover:

**Comment by martinbdz** [comment]
With `-e.wheelDelta` it is working exactly like in chrome, somehow I didn't try that.

**Comment by IonicaBizau** [comment]
Wowow, cool! Then you can create a pull request. :+1:

**Comment by martinbdz** [comment]
Okay, I'm off to work now but try to create one tomorrow morning.
