### ISSUE TITLE
zoom(z, x, y): transform may be undefined

### ISSUE THREAD

**Issue by tenKinetic** [jillix/svg.pan-zoom.js#17]
When only one argument is given the transform is created if undefined.
For more than one argument it isn't.
If the very first thing you do is call zoom with x&y, there will still be no transform and the library will break in the zoom method.

I can issue a pull request for this but first I want to see if another issue I'm having is also worth a fix here or if it's unrelated to this method or even this library.

**Comment by IonicaBizau** [comment]
> When only one argument is given the transform is created if undefined.

That's obviously a bug. It should change the zoom value. Thank you for the head's up! :four_leaf_clover: 

Pull requests are more than welcome! :+1:

**Comment by tenKinetic** [comment]
No worries. My other issue turned out to be unrelated so I issued a pull request.

**Comment by IonicaBizau** [comment]
:ship: **`2.8.0`** :tada:

**Comment by tenKinetic** [comment]
:v:
