### ISSUE TITLE
Fix zoom issue

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/svg.pan-zoom.js#2]

**Comment by IonicaBizau** [comment]
The zoom center should be the mouse position. Currently [this is broken](http://jillix.github.io/svg.pan-zoom.js/) (try to zoom in/out).

[This is the place](https://github.com/jillix/svg.pan-zoom.js/blob/8d6e7308f6cd242ce56526d3a17af6887ac1c54f/src/svg.pan-zoom.js#L136-L138) where the fix should be made, however feel free to hack it how you like.

Happy debugging! :smile: 

/cc @silviubogan

**Comment by IonicaBizau** [comment]
I'm on it. :star2: :fire:

**Comment by IonicaBizau** [comment]
I did it! 3 lines of code changed and this :bug: was :fire:. 

![](http://media.giphy.com/media/wvFrJa4aWKuvm/giphy.gif)

**Comment by gabipetrovay** [comment]
Explosive! :boom:
