### ISSUE TITLE
The zoom seems to be backwards

### ISSUE THREAD

**Issue by lcristianiim** [jillix/svg.pan-zoom.js#7]
A nice thing with the svg.pan-zoom.js is that you can zoom in/out using the middle mouse scrool.
Currently if you scrool up the page gets smaller and if you scrool down the page gets larger.

For the most applications and programs the zoom is exactly backwards.
Ex.
Google Chrome: on holding ctrl scrool up gets the page larger; scrool down gets the page smaller
Gimp: on holding ctrl scrool up gets the picture larger; scrool down gets the picture smaller
Inkscape: on holding ctrl scrool up gets the picture larger; scrool down gets the picture smaller
Blender: scrool up gets the objects seen large, scrool down gets the objects smaller

From the point of view of the user experience maybe it would be appropriate to make the zoom like all the other applications and programs.

**Comment by gabipetrovay** [comment]
Maybe this does not close the issue above. The module should adapt somehow to the user configuration. on his machine Mac/Windows/Unix. Setting it up with one configuration in mind might be annoying for the others.

**Comment by IonicaBizau** [comment]
@gabipetrovay The default configuration is the one expected, like in other apps. If the user wants to inverse the zoom, then he has to enable _natural scrolling_ (like I did: scroll up :arrow_right: smaller elements).

And for sure, there is the zoom speed option which I added in #8:

``` sh
foo.panZoom({
   zoomSpeed: 1 // inversed scrolling
});
```
